# Numpy Assignment

#### 1. Import the numpy package under the name np 

In [1]:
import numpy as np


#### 2. Print the numpy version and the configuration

In [2]:
np.__version__

'1.26.2'

#### 3. Create a null vector of size 10 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array 

In [5]:
arr = np.array([[2, 2, 3, 4], [7, 8, 9, 0]])
memorysize = arr.size
print(memorysize)

8


#### 5.How to get the documentation of the numpy add function from the command line? 

In [7]:
>>> help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1

In [8]:
Null_Vector = np.zeros(10)
Null_Vector[4] = 1
print(Null_Vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 

In [9]:
Value_Range = np.arange(10,50)
Value_Range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) 

In [11]:
Value_Range = np.arange(10,50)
reverse = Value_Range[::-1]
print(reverse)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
matr = np.arange(9).reshape(3, 3)
print(matr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [13]:
non_zero = np.nonzero([1,2,0,0,4,0])
print(non_zero)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix


In [14]:
identity= np.array([[1, 3, 5], [7, 9, 11], [13, 15, 17]])
identity

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

#### 12. Create a 3x3x3 array with random values

In [15]:
random_var = np.random.randint(20,299 , size=(3, 3, 3))
random_var

array([[[ 68, 193, 272],
        [239, 180, 266],
        [204, 223, 203]],

       [[282, 239, 198],
        [113, 252, 236],
        [269, 172, 293]],

       [[266, 190, 168],
        [173, 224, 258],
        [ 27, 297, 106]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values 

In [16]:
rand = np.random.randint(1, 999 ,size=(10, 10))
rand
print('minimum value is ', rand.min())
print('maximum value is ', rand.max())

minimum value is  31
maximum value is  990


#### 14. Create a random vector of size 30 and find the mean value 

In [17]:
randVec = np.random.randint(34,890, size=30)
print(randVec)
print('mean value is ', randVec.mean())

[841 700 848 770 805 554  37 715 381  64 833 791 887 882 348 843 735 434
 718 609 395 658 367 813 594 810 730 199 409 184]
mean value is  598.4666666666667


#### 15. Create a 2d array with 1 on the border and 0 inside 

In [18]:
border = np.ones((7, 7))
print("Arary:")
print(border)
border[1:-1, 1:-1] = 0
print(border)

Arary:
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [19]:

border = np.pad(border, pad_width=1, mode='constant', constant_values=0)
print(border)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

In [20]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [21]:
diagonal= np.diag([1, 2, 3, 4])
diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [22]:
checker = np.zeros((8,8),dtype=int)
checker[1::2,::2] = 1
checker[::2,1::2] = 1
print(checker)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [23]:
shape = (6, 7, 8)
index_1d = 100

index_3d = np.unravel_index(index_1d, shape)

print("Index (x, y, z) of the 100th element:", index_3d)


Index (x, y, z) of the 100th element: (1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function

In [24]:
checkerboard8x8 =np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

print(checkerboard8x8)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix

In [25]:
normal = np.random.random((5,5))
normal_mat = (normal - np.mean (normal)) / (np.std (normal))
print(normal_mat)

[[ 0.03626856  1.42873305  1.42895664  0.32488201 -0.56168994]
 [ 1.46916267  0.8895021   0.00933782 -0.15184294 -1.53952428]
 [-0.16752069 -0.0979976   1.46187205 -1.50635714  0.01575299]
 [ 0.59138297 -0.69713127 -0.24389227 -0.3206846  -1.3439995 ]
 [ 1.38508712 -1.02300214  1.10532175 -1.79845378 -0.69416357]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) 

In [28]:
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])


color_array = np.array([(255, 0, 0, 255),  
                        (0, 255, 0, 255),  
                        (0, 0, 255, 128)],  
                       dtype=color_dtype)


print(color_array)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 128)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [29]:
five_by_three_mat = np.random.random ((5, 3))

Three_by_two= np.random.random ((3, 2))


real_mat= np.dot(five_by_three_mat, Three_by_two)
real_mat

array([[0.86358313, 0.36720132],
       [0.54749252, 0.41378573],
       [0.51308267, 0.56628238],
       [0.21695227, 0.09433813],
       [0.51693769, 0.03751257]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [30]:
one_d = np.arange(10)
one_d[(3 < one_d) & (one_d < 8)] *= -1
one_d

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? 
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [31]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [35]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/var/folders/cv/zbwylvld3637cwzygthjxjhw0000gn/T/ipykernel_3966/548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/var/folders/cv/zbwylvld3637cwzygthjxjhw0000gn/T/ipykernel_3966/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/var/folders/cv/zbwylvld3637cwzygthjxjhw0000gn/T/ipykernel_3966/548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ?

In [36]:
Zero = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

print(np.where(Zero>0, np.ceil(Zero), np.floor(Zero)))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 8.  3. -1.  9. -6.  7.  9.  6. -8.  5.]


#### 30. How to find common values between two arrays?

In [37]:
val1 = np.arange(23)
val2= np.arange(17,34)
print(np.intersect1d(val1,val2))

[17 18 19 20 21 22]


#### 31. How to ignore all numpy warnings (not recommended)?

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)

In [38]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/cv/zbwylvld3637cwzygthjxjhw0000gn/T/ipykernel_3966/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow?

In [39]:
yesterday = np.datetime64("today") - np.timedelta64(1)
today = np.datetime64("today") 
tomorrow = np.datetime64("today") - np.timedelta64(1)
print("Yesterday was ",yesterday)
print("Todays date is ",today)
print('Tomorrow will be ',tomorrow)

Yesterday was  2024-02-27
Todays date is  2024-02-28
Tomorrow will be  2024-02-27


#### 34. How to get all the dates corresponding to the month of July 2016? 

In [41]:
import calendar
year = 2016
month = 7

first_day, last_day = calendar.monthrange(year, month)

dates_array = np.array([np.datetime64(f"{year}-{month:02d}-{day:02d}") for day in range(1, last_day + 1)])


print(dates_array)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [42]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

C= ((A + B) *  (-A / 2) )
  

print(C)


[ -2.5  -7.  -13.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [43]:
num = np.random.randint(34, 1234, 10)
print(num - num%1)
print(num // 1)
print(np.floor(num))
print(num.astype(int))
print(np.trunc(num))

[351 994 395 173 990 189 387 474 653 472]
[351 994 395 173 990 189 387 474 653 472]
[351. 994. 395. 173. 990. 189. 387. 474. 653. 472.]
[351 994 395 173 990 189 387 474 653 472]
[351. 994. 395. 173. 990. 189. 387. 474. 653. 472.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 

In [44]:
arrr = np.ones((5,5))
arr = np.arange(5) * arrr
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array 

In [45]:
def generator():
    for i in range(10):
        yield i
arr = np.fromiter(generator(),dtype=int64,count=-1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded 

In [46]:
Vect = np.linspace(0,1, 12 ,endpoint=True)[1: -1]
print(Vect)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it

In [47]:
RandVect = np.random.randint(3, 89, size = 10)
RandVect.sort()
print(RandVect)

[ 7  9 11 21 41 42 46 47 79 87]


#### 41. How to sum a small array faster than np.sum? 

In [48]:
np.add.reduce(RandVect)

390

#### 42. Consider two random array A and B, check if they are equal

In [49]:
a = np.random.randint(76,199,5)
b = np.random.randint(88,190,5)
print(a)
print(b)
equal = np.allclose(a,b)
print(equal)


[116 136 123 188 150]
[107 175 108 138 115]
False


#### 43. Make an array immutable (read-only)

In [50]:
arra = np.arange(56,990, 6)
arra.flags.writeable = False
arra[23]=8

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 

In [51]:
c = np.random.randint(23,567 , (10,2))
c
a,b = c[:,0], c[:,1]
e = np.sqrt(a**2+b**2)
f = np.arctan2(b,a)
print(e)
print(f)


[234.9553149  359.78048863 598.70276432 629.06279496 377.78433001
 385.54895928 122.06555616 522.93403026 733.48006108 273.51416782]
[1.36505372 0.22138223 0.8788382  0.49351071 0.89605538 0.96984481
 0.31656925 1.18247761 0.71883    0.13569238]


#### 45. Create random vector of size 10 and replace the maximum value by 0

In [52]:
VecMax = np.random.randint(34,78,10)
VecMax[VecMax.argmax()] = 0
print(VecMax)

[67 49 43 67 36 57 50  0 38 56]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [53]:
s = np.zeros((5,5), [('x',float),('y',float)])
s['x'], s['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(s)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 

In [54]:
x = np.random.randint(34,78, 9)
y = np.random.randint(45,100, 9)
Cauchy = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(Cauchy))

0.0


/var/folders/cv/zbwylvld3637cwzygthjxjhw0000gn/T/ipykernel_3966/3947142640.py:3: RuntimeWarning: divide by zero encountered in divide
  Cauchy = 1.0 / np.subtract.outer(x, y)


#### 48. Print the minimum and maximum representable value for each numpy scalar type

#### 49. How to print all the values of an array? 

In [55]:

Arr = np.random.randint(20, 200, size = (18, 17))
np.set_printoptions(threshold=np.inf)
print(Arr)

[[129  24 147 121 178  67  56  93 153 149 107 120 166  57 148 116 199]
 [105  85  58 115 118 189 172 143 169 195 197  27 125 161  96 162  54]
 [129 181  21  34 162 185 139 110  25  41 130  90  59  77 158 108  94]
 [ 60 159  49  34 118 194 133 185  45 170  83 118 165  66  76 152 100]
 [150  24 107 199 131 124 193 166  51  37  54  34  31 175  44  21  33]
 [ 80  48 150 156 100  56  84  48 139 132  90  36  77  84 173 108 100]
 [ 33 113  20  66  94  55 175 190 196 155  89  96 111  95 193  28 123]
 [102 197 105 105 152  72 114  36 158  39 146  84  53 152 188 152  44]
 [122  42  66  98 104 192  41 104 174 101  58  66  84 184 198  67 166]
 [175  20  54 165  60  86 199 110 109 105  90  97 109  21 100 116  63]
 [ 34 170  75 162 153 110  58 116  28 128  24 114  57 193  20  50 170]
 [184 138  78 163 149  25  79  30 128  64 159  80 166 129  89  45 154]
 [ 28 136 164  49 191  63  88 131  83  61 140  78  43 125 180  31  55]
 [ 37  92 143 137  38 180 189 181 116 183  75 128  84 159  26 163 116]
 [ 65 

#### 50. How to find the closest value (to a given scalar) in a vector? 

In [56]:
vec= np.arange(25)


sca = 5

index = np.abs(vec - sca).argmin()

clo_val = vec[index]

print(clo_val)

5


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [57]:

pos_dtype= [('x', int), ('y', int)]
color_dtype = [('r', int), ('g', int), ('b', int)]


positions = np.array([(33, 3), (44, 5)], dtype=pos_dtype)
colors = np.array([(255, 0, 0), (0, 255, 0)], dtype=color_dtype)

# Combine position and color arrays
arra = np.empty(2, dtype=[('position', pos_dtype), ('color', color_dtype)])
arra['position'] = positions
arra['color'] = colors

print(arra)



[((33, 3), (255,   0, 0)) ((44, 5), (  0, 255, 0))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances 

In [58]:
arr = np.random.randint(34, 789, size=(100,2))
piont_dist = np.sqrt(np.sum((arr - arr[:, np.newaxis])**2, axis=-1))

print(piont_dist)

[[  0.         778.56534729 772.81433734 871.08954764 124.42668524
  384.8597147  295.62983611 834.3236782  740.22293939 264.00757565
  585.04444276 394.50728764 553.66506121 813.07625719 246.78938389
  538.8144393  290.06378609 117.15374514 506.88854791 848.40084866
   86.70063437 628.26825481 437.1144015  706.23084045 925.68083052
  764.7385174  747.30248227 729.52381729 467.40346597 580.25942474
  975.12922221 327.68582514 732.08264561 403.52075535 115.27792503
  428.04205401 427.70667519 423.53984464 728.56640054 339.84849566
  865.14565248 230.31283073 433.20664815 702.4101366  937.04642361
  530.37722425 340.84600628 223.75432957 779.09242071 849.05241299
  528.92059896 116.38728453 609.70812689 252.68557537 138.92443989
  764.35724632 437.77277211 343.65680555 450.21772511 102.06860438
  199.25109786  76.40026178 209.35376758 588.15134107 831.82029309
  334.59228921 803.2988236  759.45572616 860.06976461 612.28098125
  857.2170087  918.90423875 549.10199417 705.36515366 719.7812

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [60]:
float_array = np.array([5.67, 89.49, 4.8], dtype=np.float32)

float_array.view(dtype=np.int32)[:] = float_array

print(float_array)

[7.01e-45 1.25e-43 5.61e-45]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [61]:

data = np.genfromtxt('fifty_four.txt', delimiter=',', dtype=float, missing_values='')


print(data)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? 

In [62]:
arr = np.random.randint(23, 98, 23)
for index, value in np.ndenumerate(arr):
    print(index, value)

(0,) 55
(1,) 46
(2,) 51
(3,) 23
(4,) 49
(5,) 85
(6,) 53
(7,) 83
(8,) 97
(9,) 53
(10,) 82
(11,) 77
(12,) 73
(13,) 76
(14,) 40
(15,) 96
(16,) 29
(17,) 58
(18,) 84
(19,) 97
(20,) 69
(21,) 23
(22,) 38


#### 56. Generate a generic 2D Gaussian-like array 

#### 57. How to randomly place p elements in a 2D array?

#### 59. How to sort an array by the nth column? 

In [64]:
Arr_col = np.random.randint(89,456,(7,7))
print(Arr_col)
print(Arr_col[Arr_col[:,1].argsort()])

[[176 391 345 332 144 140 112]
 [188 431 323 101 407 454 430]
 [136 306 213 277 119 254 439]
 [135 299 450 229 325 377 287]
 [308 194 301 405 112 372 370]
 [270 254 112 130 391 135 209]
 [355 282 207 153 172 249 109]]
[[308 194 301 405 112 372 370]
 [270 254 112 130 391 135 209]
 [355 282 207 153 172 249 109]
 [135 299 450 229 325 377 287]
 [136 306 213 277 119 254 439]
 [176 391 345 332 144 140 112]
 [188 431 323 101 407 454 430]]


#### 60. How to tell if a given 2D array has null columns?

In [66]:

def has_null_columns(array):
    # Convert array to NumPy array if it's not already
    array = np.array(array)
    
    # Check if any column contains only null values
    null_columns = np.any(np.all(array == 0, axis=0))
    
    return null_columns

# Example usage:
array1 = [[1, 2, 0],
          [4, 5, 0],
          [0, 0, 0]]

array2 = [[1, 0, 3],
          [4, 0, 6],
          [7, 0, 9]]

print("Array 1 has null columns:", has_null_columns(array1))
print("Array 2 has null columns:", has_null_columns(array2))


Array 1 has null columns: True
Array 2 has null columns: True


#### 61. Find the nearest value from a given value in an array 

In [67]:
def find_nearest_value(array, value):
    nearest_value = None
    min_difference = float('inf')

    for num in array:
        difference = abs(num - value)
        if difference < min_difference:
            min_difference = difference
            nearest_value = num

    return nearest_value

# Example usage:
array = [1, 3, 5, 7, 9]
value = 6
nearest = find_nearest_value(array, value)
print(f"The nearest value to {value} in the array is {nearest}")

The nearest value to 6 in the array is 5


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 

In [69]:

# Define two arrays with shapes (1, 3) and (3, 1)
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4], [5], [6]])

# Initialize a variable to store the sum
sum_result = 0

# Iterate through the arrays using an iterator
for x, y in zip(np.nditer(array1), np.nditer(array2)):
    sum_result += x + y

print("Sum of the two arrays:", sum_result)


Sum of the two arrays: 21


#### 63. Create an array class that has a name attribute

In [70]:
class NamedArray:
    def __init__(self, name, elements):
        self.name = name
        self.elements = elements

    def __repr__(self):
        return f"{self.name}: {self.elements}"

    def __str__(self):
        return f"{self.name}: {self.elements}"

# Example usage:
arr = NamedArray("MyArray", [1, 2, 3, 4, 5])
print(arr)  # Output: MyArray: [1, 2, 3, 4, 5]
print(arr.name)  # Output: MyArray
print(arr.elements)  # Output: [1, 2, 3, 4, 5]


MyArray: [1, 2, 3, 4, 5]
MyArray
[1, 2, 3, 4, 5]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [73]:

def add_one_to_indices(vector, indices):
    # Create a copy of the original vector to avoid modifying it directly
    result = np.copy(vector)
    
    # Iterate over unique indices and add 1 to corresponding elements
    unique_indices = np.unique(indices)
    for index in unique_indices:
        result[index] += 1
    
    return result

# Example usage
vector = np.array([0, 1, 2, 3, 4])
indices = np.array([1, 2, 3, 2])  # Repeated index 2
result = add_one_to_indices(vector, indices)
print("Original Vector:", vector)
print("Indices Vector:", indices)
print("Result Vector:", result)


Original Vector: [0 1 2 3 4]
Indices Vector: [1 2 3 2]
Result Vector: [0 2 3 4 4]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? 

In [74]:

def accumulate_elements(X, I, F):
    np.add.at(F, I, X)

# Example usage:
X = np.array([1, 2, 3, 4, 5])  # Vector of elements
I = np.array([0, 1, 2, 0, 1])  # Index list
F = np.zeros(3)  # Array to accumulate into

accumulate_elements(X, I, F)

print("Accumulated array F:", F)


Accumulated array F: [5. 7. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? 

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

#### 69. How to get the diagonal of a dot product? 

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? 

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 

#### 72. How to swap two rows of an array? 

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? 

#### 75. How to compute averages using a sliding window over an array? 

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

#### 77. How to negate a boolean, or to change the sign of a float inplace?

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? 

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) 

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 

#### 82. Compute a matrix rank

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

#### 88. How to implement the Game of Life using numpy arrays?

#### 89. How to get the n largest values of an array

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 

#### 91. How to create a record array from a regular array?

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods 

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? 


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

#### 95. Convert a vector of ints into a matrix binary representation

#### 96. Given a two dimensional array, how to extract unique rows? 

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). 

In [68]:
a = np.array([[2.5, -7.5, 8], [0, -2, 4.5]])
print(a)

[[ 2.5 -7.5  8. ]
 [ 0.  -2.   4.5]]
